image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  AZURE_SQL_HOST: azuresql
  AZURE_SQL_USER: sa
  AZURE_SQL_DATABASE: TestDb
  AZURE_SQL_PASSWORD: YourStrong@Passw0rd

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: itsplus/s2shape-sql-test
      alias: azuresql

  script:
    - dotnet build
    - dotnet test
